language: d

os:
  - linux
  - osx
  
d:
  - dmd-2.069.2
  - ldc-0.16.1
  
matrix:
    allow_failures:
        - d: ldc-0.16.1
    exclude:
        - d: ldc-0.16.1
          os: osx
  
script:
    - dub build --compiler=${DC}
    - echo "Hello world!" > "to_delete.txt"
    - dub run :put --compiler=${DC} -- "to_delete.txt"
    - mkdir testdir
    - echo "Hello world!" > "testdir/hello.txt"
    - dub run :put --compiler=${DC} -- "testdir"
