language: d

os:
  - linux
  - osx
  
d:
  - dmd-2.069.2
  - ldc-0.16.1
  - gdc-4.9.2
  
matrix:
    allow_failures:
        - d: gdc-4.9.2
        - d: ldc-0.16.1
    exclude:
        - d: gdc-4.9.2
          os: osx
  
script:
    - echo "Hello world!" > "to_delete.txt"
    - dub run --compiler=${DC} -- "to_delete.txt"
    - mkdir testdir
    - echo "Hello world!" > "testdir/hello.txt"
    - dub run --compiler=${DC} -- "testdir"
