language: d

os:
  - linux
  - osx

d:
  - dmd
  - ldc

script:
    - dub build --compiler=${DC}
    - echo "Hello world!" > "to_delete.txt"
    - dub --single examples/put.d --compiler=${DC} -- "to_delete.txt"
    - mkdir testdir
    - echo "Hello world!" > "testdir/hello.txt"
    - dub --single examples/put.d --compiler=${DC} -- "testdir"
    - dub --single examples/manage.d --compiler=${DC} -- --list
